### ISSUE TITLE
Only a few messages shown

### ISSUE THREAD

**Issue by DarthApron** [devadvance/sms-backup-reader-2#1]
Hi,
I'm glad that the new SMS Backup Reader 2 is able to read my backup as the Java app fails gloriously.
Unfortunately the new web app only shows a handful of messages.
According to SMS Backup & Restore it has 7360 messages, but the web app only shows the first 53 of them.
The XML itself is just 2,8 MB in size.

Thanks for your help. 👍

**Comment by devadvance** [comment]
Merged PR to fix
