### ISSUE TITLE
contact name not showing up

### ISSUE THREAD

**Issue by johnghadimi** [devadvance/sms-backup-reader-2#2]
The xml file has the filed contact_name. Is there a reason or known issue for that to not show up in SMS Backup Reader? It's pretty tough identifying the conversations via the phone numbers.

**Comment by charleskilbourne** [comment]
I have resolved this issue in this pull request https://github.com/devadvance/sms-backup-reader-2/pull/5

I don't know if the original author is still maintaining this repo

**Comment by devadvance** [comment]
@charleskilbourne I'll review the PR and make sure it runs on my end as well. If it does I'll push to the live site.

**Comment by devadvance** [comment]
Merged
